# Generated by Django 5.2.8 on 2026-08-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_pipeline_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='The permission set. THIS is what decides module access — see accounts/crm_permissions.py. `role` above is a job-function label and grants nothing on its own.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customrole'),
        ),
    ]
