# Generated by Django 5.2.8 on 2026-08-31 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userpermission_can_all'),
        ('teams', '0004_teampermission_can_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_team',
            field=models.ForeignKey(blank=True, help_text='The team this person MANAGES. Set only by a super admin. It opens the Users module for them and pins every write they make to this one team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='teams.team'),
        ),
    ]
