# Generated by Django 5.2.8 on 2026-09-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_add_attendance_module'),
        ('accounts', '0033_add_credit_control_module'),
    ]

    operations = [
    ]
