# Generated by Django 5.2.8 on 2026-09-09 18:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_event', '0027_remove_bookevent_payment_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditControlDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Reached', 'Reached'), ('Resolved', 'Resolved'), ('Not Reached', 'Not Reached')], default='Not Reached', max_length=20)),
                ('status_group', models.CharField(choices=[('Not Attempted', 'Not Attempted'), ('Attempted', 'Attempted'), ('Ongoing', 'Ongoing'), ('Technical Issues', 'Technical Issues')], default='Attempted', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'credit_control_dispositions',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CreditControlLead',
            fields=[
                ('invoice', models.OneToOneField(db_column='invoice_number', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credit_control', serialize=False, to='book_event.bookevent', to_field='invoice_number')),
                ('bucket', models.CharField(choices=[('active', 'Active'), ('not_invoiced', 'Not invoiced yet'), ('spex', 'SpEx & Speaker Table'), ('done', 'Done')], db_index=True, default='active', max_length=20)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('handed_off_at', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, default='', max_length=100)),
                ('remark', models.TextField(blank=True, default='')),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('callback_date', models.DateField(blank=True, null=True)),
                ('last_touched_at', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('done_reason', models.CharField(blank=True, default='', max_length=120)),
                ('invoice_type', models.CharField(blank=True, choices=[('Blind Invoice', 'Blind Invoice'), ('Requested', 'Requested')], default='', max_length=20)),
                ('invoice_type_source', models.CharField(blank=True, choices=[('rule', 'Deterministic rule'), ('model', 'Classifier'), ('manual', 'Human override')], default='', max_length=10)),
                ('invoice_type_override', models.CharField(blank=True, choices=[('Blind Invoice', 'Blind Invoice'), ('Requested', 'Requested')], default='', max_length=20)),
                ('invoice_type_basis', models.CharField(blank=True, default='', max_length=200)),
                ('invoice_type_quote', models.TextField(blank=True, default='')),
                ('invoice_type_evidence_date', models.DateField(blank=True, null=True)),
                ('invoice_type_confidence', models.FloatField(blank=True, null=True)),
                ('invoice_type_model', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_type_prompt_version', models.CharField(blank=True, default='', max_length=20)),
                ('invoice_type_attempts', models.PositiveIntegerField(default=0)),
                ('invoice_type_error', models.CharField(blank=True, default='', max_length=300)),
                ('invoice_type_at', models.DateTimeField(blank=True, null=True)),
                ('handoff_brief', models.TextField(blank=True, default='')),
                ('handoff_brief_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_control_leads', to=settings.AUTH_USER_MODEL)),
                ('last_touched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_control_touches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_control_leads',
            },
        ),
        migrations.CreateModel(
            name='CreditControlTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(blank=True, default='', max_length=100)),
                ('remark', models.TextField(blank=True, default='')),
                ('fields_changed', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touches', to='credit_control.creditcontrollead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_control_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_control_touches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditcontrollead',
            index=models.Index(fields=['bucket', 'assigned_to'], name='credit_cont_bucket_bdf4d9_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcontrollead',
            index=models.Index(fields=['bucket', 'first_seen'], name='credit_cont_bucket_40f539_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcontrollead',
            index=models.Index(fields=['callback_date'], name='credit_cont_callbac_5f86ff_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcontroltouch',
            index=models.Index(fields=['created_at', 'user'], name='credit_cont_created_d88b55_idx'),
        ),
    ]
