# Generated by Django 5.2.8 on 2026-09-10 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcontrollead',
            name='resolved_after_effort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditcontrollead',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcontrollead',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_control_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcontrollead',
            name='resolved_disposition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
