# Generated by Django 5.2.8 on 2026-09-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_control', '0002_creditcontrollead_resolved_after_effort_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcontrollead',
            name='handed_off_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_control_handed_over', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditcontrollead',
            name='handoff_disposition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='creditcontrollead',
            name='handoff_remark',
            field=models.TextField(blank=True, default=''),
        ),
    ]
