# Generated by Django 5.2.8 on 2026-09-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_control', '0003_creditcontrollead_handed_off_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcontrollead',
            name='invoice_type_basis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
