# Generated by Django 5.2.8 on 2026-08-10 21:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_submission_date', models.DateField(blank=True, null=True)),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('speaker_email_ref', models.EmailField(blank=True, default='', max_length=254)),
                ('research_email_ref', models.EmailField(blank=True, default='', max_length=254)),
                ('speaker_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('linkedin_speaker', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_company', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_followers', models.PositiveIntegerField(blank=True, null=True)),
                ('nos', models.BooleanField(blank=True, default=False)),
                ('closeness_to_topic', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('closeness_to_region', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('clear_solution_to_challenges', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('case_study_results_examples', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('not_obvious_sales_pitch', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('company_profile_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('proposal_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, db_index=True, default='', max_length=1)),
                ('session_location_on_agenda', models.CharField(blank=True, default='', max_length=100)),
                ('internal_footnotes', models.TextField(blank=True, default='')),
                ('feedback_to_speaker', models.TextField(blank=True, default='')),
                ('proposal_received', models.TextField(blank=True, default='')),
                ('theme', models.CharField(blank=True, default='', max_length=255)),
                ('agenda_addition', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_paper_reviews', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_paper_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper Review',
                'verbose_name_plural': 'Paper Reviews',
                'db_table': 'paper_reviews',
                'ordering': ['-paper_submission_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('to_addresses', models.JSONField(blank=True, default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('fallback', 'Fallback'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('included_internal_footnotes', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('paper_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='paper_review.paperreview')),
            ],
            options={
                'verbose_name': 'Paper Review Notification',
                'verbose_name_plural': 'Paper Review Notifications',
                'db_table': 'paper_review_notification_logs',
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='paperreview',
            index=models.Index(fields=['event_code'], name='paper_revie_event_c_4e2532_idx'),
        ),
        migrations.AddIndex(
            model_name='paperreview',
            index=models.Index(fields=['paper_submission_date'], name='paper_revie_paper_s_07b17f_idx'),
        ),
        migrations.AddIndex(
            model_name='paperreview',
            index=models.Index(fields=['grade'], name='paper_revie_grade_59b239_idx'),
        ),
        migrations.AddIndex(
            model_name='paperreview',
            index=models.Index(fields=['created_at'], name='paper_revie_created_5e666f_idx'),
        ),
        migrations.AddIndex(
            model_name='paperreview',
            index=models.Index(fields=['email'], name='paper_revie_email_2ddf13_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='paper_revie_status_d064f6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['sent_at'], name='paper_revie_sent_at_b0abf5_idx'),
        ),
    ]
