# Generated by Django 5.2.8 on 2026-08-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('fallback', 'Fallback'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, max_length=20),
        ),
    ]
