# Generated by Django 5.2.8 on 2026-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0002_alter_notificationlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperreview',
            name='import_batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
