# Generated by Django 5.2.8 on 2026-08-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0003_paperreview_import_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperreview',
            name='grade',
            field=models.CharField(blank=True, db_index=True, default='', max_length=5),
        ),
    ]
