# Generated by Django 5.2.8 on 2026-08-13 22:13

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0004_alter_paperreview_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paperreview',
            index=models.Index(models.F('event_code'), django.db.models.functions.text.Lower('email'), name='paper_review_dupe_idx'),
        ),
    ]
