# Generated by Django 5.2.8 on 2026-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='import_batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
