# Generated by Django 5.2.8 on 2026-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_capacity_expected_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closes',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
