# Generated by Django 5.2.8 on 2026-08-31 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=20)),
                ('record_id', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'data_api_deleted_records',
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['resource', 'deleted_at'], name='dapi_deleted_res_at_idx')],
            },
        ),
    ]
