# Generated by Django 5.2.8 on 2026-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_delegate', '0010_bookdelegate_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdelegate',
            name='import_batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
