"""
Replace the delegate key (invoice, email) with (invoice, email, first_name,
last_name), so two people sharing one email address can both be delegates on
one invoice. See the note on BookDelegate.Meta.constraints for why.

WHY THE DROP IS HAND-WRITTEN
A plain AlterUniqueTogether emits `ALTER TABLE ... DROP CONSTRAINT <name>` for
the two-column key, and neither half of that is safe to assume here.

  1. The NAME was generated by the schema editor when 0001_initial created the
     table, so it is not written down anywhere in this repository.
  2. The constraint may not EXIST. On the development database it does not:
     `book_delegates` carries a plain, non-unique index on
     (invoice_number, email) and no unique constraint at all, while
     django_migrations records 0001_initial as applied. That is the same
     recorded-state-versus-real-schema drift `manage.py sync_indexes` exists to
     report, and a DROP CONSTRAINT against it aborts the migration.

So the drop finds the old key by its COLUMNS rather than by its name, covers
both spellings Postgres can hold it in (a unique constraint, or a bare unique
index left behind by one), and does nothing when it is already absent.

Adding the new key is a plain AddConstraint, so Django owns its name and emits
whatever DDL each backend needs.

NUMBERED 0017, NOT 0016. This database already records a `0016_bookingshare` as
applied and its file is not in this tree, so 0016 is taken. If that file
reappears, both it and this one will depend on 0015 and Django will ask for
`makemigrations --merge`; that merge is the whole fix, no DDL changes.
"""
from django.db import migrations, models

TABLE = "book_delegates"
OLD_COLUMNS = ["email", "invoice_number"]      # sorted, to compare as a set

# Unique CONSTRAINTS on exactly the old column pair, by column rather than name.
FIND_CONSTRAINT = """
    SELECT c.conname
      FROM pg_constraint c
     WHERE c.conrelid = %s::regclass
       AND c.contype  = 'u'
       AND (SELECT array_agg(a.attname::text ORDER BY a.attname)
              FROM unnest(c.conkey) AS k
              JOIN pg_attribute a
                ON a.attrelid = c.conrelid AND a.attnum = k) = %s::text[]
"""

# Unique INDEXES on the same pair that no constraint owns. Dropping the
# constraint takes its own backing index with it, so this catches only an index
# created on its own — by hand, or by a restore that kept indexes and lost
# constraints.
FIND_INDEX = """
    SELECT i.relname
      FROM pg_index x
      JOIN pg_class i ON i.oid = x.indexrelid
     WHERE x.indrelid   = %s::regclass
       AND x.indisunique
       AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = x.indexrelid)
       AND (SELECT array_agg(a.attname::text ORDER BY a.attname)
              FROM unnest(x.indkey) AS k
              JOIN pg_attribute a
                ON a.attrelid = x.indrelid AND a.attnum = k) = %s::text[]
"""


def drop_old_unique(apps, schema_editor):
    model = apps.get_model("book_delegate", "BookDelegate")
    if schema_editor.connection.vendor != "postgresql":
        # Every other backend gets Django's own path. SQLite in particular has
        # to rebuild the table, and the schema editor is the only thing that
        # knows how.
        schema_editor.alter_unique_together(model, [("invoice", "email")], [])
        return

    with schema_editor.connection.cursor() as cur:
        cur.execute(FIND_CONSTRAINT, [TABLE, OLD_COLUMNS])
        for (name,) in cur.fetchall():
            schema_editor.execute(
                f'ALTER TABLE {schema_editor.quote_name(TABLE)} '
                f'DROP CONSTRAINT {schema_editor.quote_name(name)}'
            )
        cur.execute(FIND_INDEX, [TABLE, OLD_COLUMNS])
        for (name,) in cur.fetchall():
            schema_editor.execute(f'DROP INDEX {schema_editor.quote_name(name)}')


def restore_old_unique(apps, schema_editor):
    """
    Put the two-column key back.

    Deliberately NOT guarded: by the time this runs the new key has already
    been dropped by the reverse of AddConstraint, so if any invoice now holds
    two people on one email address, Postgres refuses and says which rows. That
    is the correct answer to reversing this migration over data it no longer
    fits, and a silent skip would leave the database claiming a key it has not
    got.
    """
    model = apps.get_model("book_delegate", "BookDelegate")
    if schema_editor.connection.vendor != "postgresql":
        schema_editor.alter_unique_together(model, [], [("invoice", "email")])
        return
    schema_editor.execute(
        f'ALTER TABLE {schema_editor.quote_name(TABLE)} '
        f'ADD CONSTRAINT book_delegates_invoice_email_uniq '
        f'UNIQUE (invoice_number, email)'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("book_delegate", "0015_updated_at_order_index"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="bookdelegate",
                    unique_together=set(),
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_old_unique, restore_old_unique),
            ],
        ),
        migrations.AddConstraint(
            model_name="bookdelegate",
            constraint=models.UniqueConstraint(
                fields=("invoice", "email", "first_name", "last_name"),
                name="book_delegates_invoice_person_uniq",
            ),
        ),
    ]
