# Generated by Django 5.2.8 on 2026-09-03 21:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_delegate', '0018_delegate_date_overrides'),
        ('book_event', '0025_payment_status_pending_default'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookdelegate',
            index=models.Index(models.F('event_code'), django.db.models.functions.text.Lower('email'), name='book_delegates_event_email_idx'),
        ),
    ]
