# Generated by Django 5.2.8 on 2026-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_delegate', '0019_bookdelegate_book_delegates_event_email_idx'),
    ]

    operations = [
        # The choices change alone is metadata: PostgreSQL has no constraint
        # behind them, so a row still holding one of the two dropped values would
        # survive as a value nothing can now set, read or filter for. Zero rows
        # hold one here (13,813 Pending / 1,699 Confirmed), so this is a no-op on
        # this database and insurance on any other.
        migrations.RunSQL(
            """UPDATE book_delegates SET attendance = 'Pending'
                 WHERE attendance NOT IN ('Pending', 'Confirmed')""",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='bookdelegate',
            name='attendance',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], db_index=True, default='Pending', max_length=20),
        ),
    ]
