# Generated by Django 5.2.8 on 2026-09-09 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotCall',
            fields=[
                ('call_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('shift_date', models.DateField(db_index=True)),
                ('disposition', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'hubspot_calls',
                'indexes': [models.Index(fields=['shift_date', 'owner_id'], name='hubspot_cal_shift_d_8c75a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='HubSpotContact',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contact_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=50)),
                ('direct_phone', models.CharField(blank=True, default='', max_length=50)),
                ('times_called', models.IntegerField(blank=True, null=True)),
                ('times_called_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hubspot_contacts',
                'indexes': [models.Index(fields=['fetched_at'], name='hubspot_con_fetched_74f5dc_idx')],
            },
        ),
    ]
