# Generated by Django 5.2.8 on 2026-09-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspotcall',
            name='owner_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
    ]
