# Generated by Django 5.2.8 on 2026-09-10 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0002_hubspotcall_owner_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotPurposeCount',
            fields=[
                ('purpose', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mailable_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hubspot_purpose_counts',
                'ordering': ['purpose'],
            },
        ),
        migrations.AddField(
            model_name='hubspotcontact',
            name='last_call_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubspotcontact',
            name='last_call_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
