# Generated by Django 5.2.8 on 2026-09-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_central', '0010_link_key_drop_duplicate_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
