# Generated by Django 5.2.8 on 2026-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0025_payment_status_pending_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Free', 'Free'), ('Credit Pending (Free)', 'Credit Pending (Free)'), ('Credit Pending (Paid)', 'Credit Pending (Paid)'), ('Credit Transferred', 'Credit Transferred'), ('Paid (Transferred)', 'Paid (Transferred)'), ('IQ Staff', 'IQ Staff')], db_index=True, default='Pending', max_length=30),
        ),
    ]
