"""
book_event/models.py
─────────────────────
Invoice-level booking entity.

Design decisions:
- invoice_number is PRE-GENERATED by the website — never auto-created here.
- Payment status lives here; delegates inherit it at read-time via @property.
- Financial fields map exactly to the Zoho payload field names.
- sales_executive is auto-assigned based on event→user mapping.
"""
from django.conf import settings
from django.db import models
from django.utils import timezone


class BookEvent(models.Model):
    class PaymentStatus(models.TextChoices):
        PENDING              = "Pending",              "Pending"
        PAID                 = "Paid",                 "Paid"
        UNPAID               = "Unpaid",               "Unpaid"
        CANCELLED            = "Cancelled",            "Cancelled"
        REFUNDED             = "Refunded",             "Refunded"
        FREE                 = "Free",                 "Free"
        CREDIT_PENDING_FREE  = "Credit Pending (Free)",  "Credit Pending (Free)"
        CREDIT_PENDING_PAID  = "Credit Pending (Paid)",  "Credit Pending (Paid)"
        CREDIT_TRANSFERRED   = "Credit Transferred",     "Credit Transferred"
        PAID_TRANSFERRED     = "Paid (Transferred)",     "Paid (Transferred)"
        # A booking held by an IQ-Hub staff member rather than a paying delegate.
        # UNPAID and FREE stay declared below them: no row in the export carries
        # "Unpaid", and exactly one delegate override carries "Free", but dropping
        # a choice a stored value uses would make that row fail full_clean() and
        # vanish from every choice-validated filter. The Bookings UI no longer
        # OFFERS them (frontend/src/lib/constants.js PAYMENT_STATUSES); the model
        # continues to accept what is already in the database.
        IQ_STAFF             = "IQ Staff",               "IQ Staff"

    class PaymentType(models.TextChoices):
        STRIPE        = "Stripe",        "Stripe"
        BANK          = "Bank",          "Bank"

    class PaidOrFree(models.TextChoices):
        PAID = "Paid", "Paid"
        FREE = "Free", "Free"

    class TicketTier(models.TextChoices):
        SEB     = "SEB",     "SEB"
        EB      = "EB",      "EB"
        REGULAR = "Regular", "Regular"

    class Currency(models.TextChoices):
        USD   = "USD",   "USD"
        GBP   = "GBP",   "GBP"
        EUR   = "EUR",   "EUR"
        AED   = "AED",   "AED"
        SGD   = "SGD",   "SGD"
        INR   = "INR",   "INR"
        OTHER = "OTHER", "OTHER"

    class Source(models.TextChoices):
        MANUAL  = "manual",  "Manual"
        WEBSITE = "website", "Website"

    # ── Identifiers ────────────────────────────────────────────────────────────
    invoice_number  = models.CharField(max_length=100, unique=True, db_index=True)
    event_code      = models.CharField(max_length=50, db_index=True)
    event_name      = models.CharField(max_length=255, blank=True, default="")
    event_date      = models.DateField(null=True, blank=True)
    invoice_date    = models.DateField(null=True, blank=True)
    booking_code    = models.CharField(max_length=100, blank=True, default="")
    edition         = models.IntegerField(null=True, blank=True, db_index=True)
    # See events/models.py for the rationale — one value per load_zoho_export run.
    import_batch_id = models.UUIDField(null=True, blank=True, db_index=True)

    # ── Ownership ──────────────────────────────────────────────────────────────
    sales_executive = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="bookings",
    )
    team_leader = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="team_bookings",
    )

    # ── Company / contact (denormalised for fast table queries) ────────────────
    company_name  = models.CharField(max_length=255, blank=True, default="")
    contact_name  = models.CharField(max_length=255, blank=True, default="")
    contact_email = models.EmailField(blank=True, default="")
    contact_phone = models.CharField(max_length=50, blank=True, default="")
    accounts_contact_email = models.EmailField(blank=True, default="")

    # ── Financial (Zoho field mapping) ─────────────────────────────────────────

    discount             = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount_code        = models.CharField(max_length=100, blank=True, default="")
    pre_tax_amount       = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    tax_amount           = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    total_amount         = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    add_ons_total_amount = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    currency             = models.CharField(max_length=10, choices=Currency.choices, default=Currency.USD)
    ticket_tier          = models.CharField(max_length=50, choices=TicketTier.choices, blank=True, default="")
    delegate_count       = models.PositiveIntegerField(default=1)

    # ── Website intake metadata ────────────────────────────────────────────────
    source    = models.CharField(max_length=20, choices=Source.choices, default=Source.MANUAL, db_index=True)
    form_name = models.CharField(max_length=255, blank=True, default="")
    form_url  = models.CharField(max_length=500, blank=True, default="")
    packages  = models.JSONField(default=list, blank=True)

    # ── Payment ────────────────────────────────────────────────────────────────
    payment_status = models.CharField(
        max_length=30, choices=PaymentStatus.choices,
        default=PaymentStatus.PENDING, db_index=True,
    )
    payment_date     = models.DateField(null=True, blank=True)
    payment_due_date = models.DateField(null=True, blank=True)
    payment_type = models.CharField(
        max_length=30, blank=True, default="",
        choices=PaymentType.choices,
    )
    paid_or_free = models.CharField(
        max_length=20, choices=PaidOrFree.choices, blank=True, default="",
    )
    paid_free = models.CharField(max_length=20, blank=True, default="")  # legacy

    # ── Reference ──────────────────────────────────────────────────────────────
    reference    = models.CharField(max_length=100, blank=True, default="")
    parent_code  = models.CharField(max_length=100, blank=True, default="")
    request_date = models.DateField(null=True, blank=True)
    notes        = models.TextField(blank=True, default="")
    add_ons      = models.TextField(blank=True, default="")
    attendance   = models.CharField(max_length=100, blank=True, default="")
    created_at   = models.DateTimeField(default=timezone.now)
    updated_at   = models.DateTimeField(auto_now=True)
    updated_by   = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="updated_bookings",
    )

    class Meta:
        db_table = "book_events"
        ordering = ["-created_at"]
        indexes  = [
            models.Index(fields=["invoice_number"]),
            models.Index(fields=["event_code"]),
            models.Index(fields=["payment_status"]),
            models.Index(fields=["contact_email"]),
            models.Index(fields=["company_name"]),
            models.Index(fields=["created_at"]),
            models.Index(fields=["updated_at"]),
            models.Index(fields=["ticket_tier"]),
            models.Index(fields=["paid_or_free"]),
            # request_date and invoice_date carried NO index of any kind, and both
            # are read on every bookings request: request_date is the default sort
            # (book_delegate/views.py ordering = ["-_sort_request_date"]) and the
            # pair is the period window (period_date_fields).
            #
            # Spelled as expressions rather than fields=["-request_date", "-id"]
            # because that form emits DESC NULLS FIRST, which is a DIFFERENT index
            # from the DESC NULLS LAST the DDL specifies. These names and the
            # column lists must stay byte-identical to the CREATE INDEX statements
            # in backend/sql/2026_08_perf_indexes.sql.
            models.Index(
                models.F("request_date").desc(nulls_last=True),
                models.F("id").desc(),
                name="book_events_reqdate_id_idx",
            ),
            models.Index(
                models.F("invoice_date").desc(nulls_last=True),
                models.F("id").desc(),
                name="book_events_invdate_id_idx",
            ),
        ]

    def __str__(self):
        return f"{self.invoice_number} — {self.event_code}"

    def save(self, *args, **kwargs):
        if not self.invoice_number:
            raise ValueError("invoice_number must be pre-generated by the website.")

        # Did either date move? Read once, here, as two columns — save() did not
        # previously load the stored row for any reason, so there is nothing to
        # reuse and this is a genuinely new read. It is two columns keyed on the
        # pk, and it only happens on UPDATE: a create has no delegates yet, so
        # there is nothing to propagate to.
        _dates_changed = False
        if self.pk:
            _prev = (BookEvent.objects
                     .filter(pk=self.pk)
                     .values_list("request_date", "invoice_date")
                     .first())
            if _prev is not None:
                # BOTH SIDES NORMALISED THROUGH to_python BEFORE COMPARING.
                # The database returns datetime.date, but an in-memory instance
                # can legitimately hold a STRING — BookEvent.objects.create(
                # request_date="2026-01-01") leaves the attribute a str until it
                # is reloaded, and several importers assign ISO strings directly.
                # Comparing date(2026,1,1) to "2026-01-01" is always unequal, so
                # without this every save of an unchanged invoice would rewrite
                # every one of its delegate rows.
                _rf = self._meta.get_field("request_date")
                _if = self._meta.get_field("invoice_date")
                _dates_changed = (
                    _rf.to_python(_prev[0]) != _rf.to_python(self.request_date)
                    or _if.to_python(_prev[1]) != _if.to_python(self.invoice_date)
                )
        if self.event_code:
            import re
            match = re.search(r'(\d{2,4})$', self.event_code)
            if match:
                num_str = match.group(1)
                self.edition = int(f"20{num_str}" if len(num_str) == 2 else num_str)
                self.event_code = re.sub(r'\s*-?\s*\d{2,4}$', '', self.event_code).strip()
            
            # Dynamically fetch clean name from master Event catalogue and append edition year
            from events.models import Event
            master_event = Event.objects.filter(event_code=self.event_code).first()
            if master_event:
                clean_name = re.sub(r'\s*\d{4}$', '', master_event.name).strip()
                if self.edition:
                    self.event_name = f"{clean_name} {self.edition}"
                else:
                    self.event_name = clean_name
        super().save(*args, **kwargs)

        # THE ONE SANCTIONED queryset .update() IN THIS CODEBASE.
        #
        # The project rule is per-object save() because BookDelegate.save() is
        # load-bearing; it derives edition and event_code, inherits booking_code,
        # and reads the previous payment status to decide delegate_count. None of
        # that is relevant here. This writes exactly one DERIVED column and runs no
        # derivation, so routing it through save() would re-run all of the above
        # plus one extra SELECT for every delegate on the invoice, which is the cost
        # this workstream exists to remove. Scope is deliberately one column, one
        # table, one invoice; anything wider goes back through save().
        #
        # Filtered on invoice_id, NOT on pk, and NOT on invoice_number.
        # BookDelegate.invoice is a to_field FK: field.name is "invoice",
        # field.attname is "invoice_id", and field.column is "invoice_number".
        # Only the first two are ORM query names — filter(invoice_number=...)
        # raises FieldError, because invoice_number is the DB column and not a
        # field Django will resolve. invoice_id is the attname and holds the
        # invoice-number STRING, so this compares number to number. Comparing to
        # self.pk would compare a varchar column to an integer and match nothing.
        # The emitted SQL is:
        #     UPDATE "book_delegates" SET "booked_on" = %s
        #     WHERE "book_delegates"."invoice_number" = %s
        if _dates_changed:
            from book_delegate.models import BookDelegate
            BookDelegate.objects.filter(invoice_id=self.invoice_number).update(
                booked_on=self.request_date or self.invoice_date
            )

    @classmethod
    def auto_assign_sales(cls, event_code: str):
        """
        The sales executive for `event_code`, as the EVENTS TAB defines it.

        One resolver for every path that creates or re-homes a booking (website
        intake, the Bookings modal, the importers) so a manually-entered booking
        and a webhook-created one on the same event cannot end up owned by
        different people.

        Order, and why:
          1. Event.sales_executive — the FK the Events tab writes, and which
             Event.save() keeps in step with the `sales_team` text field in both
             directions (events/models.py:104-152). This is the authoritative
             answer whenever the event has been maintained through the UI.
          2. User.assigned_events — the older m2m this method used exclusively.
             Kept as the fallback so events assigned only through that relation
             still resolve exactly as they did before.

        Returns None when neither answers; callers must treat "unassigned" as a
        legitimate outcome rather than an error, because an event can genuinely
        have no sales executive yet.
        """
        from accounts.models import User
        from events.models import Event

        event = (
            Event.objects
            .filter(event_code=event_code)
            .select_related("sales_executive")
            .first()
        )
        if event and event.sales_executive_id:
            return event.sales_executive
        return (
            User.objects
            .filter(role=User.Role.SALES, assigned_events__event_code=event_code)
            .first()
        )

class WebhookLog(models.Model):
    class Status(models.TextChoices):
        SUCCESS   = "success",   "Success"
        FAILED    = "failed",    "Failed"
        DUPLICATE = "duplicate", "Duplicate"

    source_ip      = models.GenericIPAddressField(null=True, blank=True)
    payload        = models.JSONField(default=dict)
    headers        = models.JSONField(default=dict)
    response       = models.JSONField(default=dict)
    status         = models.CharField(max_length=20, choices=Status.choices, default=Status.SUCCESS)
    http_status    = models.PositiveIntegerField(default=200)
    invoice_number = models.CharField(max_length=100, blank=True, default="")
    event_code     = models.CharField(max_length=50, blank=True, default="")
    error_message  = models.TextField(blank=True, default="")
    created_at     = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = "webhook_logs"
        ordering = ["-created_at"]
        indexes  = [
            models.Index(fields=["status"]),
            models.Index(fields=["created_at"]),
            models.Index(fields=["invoice_number"]),
        ]

    def __str__(self):
        return f"[{self.status}] {self.invoice_number or '—'} @ {self.created_at:%Y-%m-%d %H:%M}"


class SyncLog(models.Model):
    class Status(models.TextChoices):
        SUCCESS = "success", "Success"
        FAILED  = "failed",  "Failed"

    dataset        = models.CharField(max_length=50, unique=True)
    last_synced_at = models.DateTimeField(null=True, blank=True)
    last_status    = models.CharField(max_length=20, choices=Status.choices, default=Status.SUCCESS)
    records_synced = models.IntegerField(default=0)
    error_message  = models.TextField(blank=True, default="")

    class Meta:
        db_table = "sync_logs"

    def __str__(self):
        return f"{self.dataset}: {self.last_status} ({self.records_synced} rows) at {self.last_synced_at}"
