"""
book_event/models.py
─────────────────────
Invoice-level booking entity.

Design decisions:
- invoice_number is PRE-GENERATED by the website — never auto-created here.
- Payment status lives here; delegates inherit it at read-time via @property.
- Financial fields map exactly to the Zoho payload field names.
- sales_executive is auto-assigned based on event→user mapping.
"""
from django.conf import settings
from django.core.exceptions import FieldDoesNotExist
from django.db import models
from django.utils import timezone

from book_event.booking_code_canonical import canonicalize_on_save


class BookEvent(models.Model):
    class PaymentStatus(models.TextChoices):
        PENDING              = "Pending",              "Pending"
        PAID                 = "Paid",                 "Paid"
        UNPAID               = "Unpaid",               "Unpaid"
        CANCELLED            = "Cancelled",            "Cancelled"
        REFUNDED             = "Refunded",             "Refunded"
        FREE                 = "Free",                 "Free"
        CREDIT_PENDING_FREE  = "Credit Pending (Free)",  "Credit Pending (Free)"
        CREDIT_PENDING_PAID  = "Credit Pending (Paid)",  "Credit Pending (Paid)"
        CREDIT_TRANSFERRED   = "Credit Transferred",     "Credit Transferred"
        PAID_TRANSFERRED     = "Paid (Transferred)",     "Paid (Transferred)"
        # A booking held by an IQ-Hub staff member rather than a paying delegate.
        # UNPAID and FREE stay declared below them: no row in the export carries
        # "Unpaid", and exactly one delegate override carries "Free", but dropping
        # a choice a stored value uses would make that row fail full_clean() and
        # vanish from every choice-validated filter. The Bookings UI no longer
        # OFFERS them (frontend/src/lib/constants.js PAYMENT_STATUSES); the model
        # continues to accept what is already in the database.
        IQ_STAFF             = "IQ Staff",               "IQ Staff"

    class PaymentType(models.TextChoices):
        STRIPE        = "Stripe",        "Stripe"
        BANK          = "Bank",          "Bank"

    class PaidOrFree(models.TextChoices):
        PAID = "Paid", "Paid"
        FREE = "Free", "Free"

    class TicketTier(models.TextChoices):
        SEB     = "SEB",     "SEB"
        EB      = "EB",      "EB"
        REGULAR = "Regular", "Regular"

    class Currency(models.TextChoices):
        USD   = "USD",   "USD"
        GBP   = "GBP",   "GBP"
        EUR   = "EUR",   "EUR"
        AED   = "AED",   "AED"
        SGD   = "SGD",   "SGD"
        INR   = "INR",   "INR"
        OTHER = "OTHER", "OTHER"

    class Source(models.TextChoices):
        MANUAL  = "manual",  "Manual"
        WEBSITE = "website", "Website"

    # ── Identifiers ────────────────────────────────────────────────────────────
    invoice_number  = models.CharField(max_length=100, unique=True, db_index=True)
    event_code      = models.CharField(max_length=50, db_index=True)
    event_name      = models.CharField(max_length=255, blank=True, default="")
    event_date      = models.DateField(null=True, blank=True)
    invoice_date    = models.DateField(null=True, blank=True)
    booking_code    = models.CharField(max_length=100, blank=True, default="")
    edition         = models.IntegerField(null=True, blank=True, db_index=True)
    # See events/models.py for the rationale — one value per load_zoho_export run.
    import_batch_id = models.UUIDField(null=True, blank=True, db_index=True)

    # ── Ownership ──────────────────────────────────────────────────────────────
    sales_executive = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="bookings",
    )
    team_leader = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="team_bookings",
    )

    # ── Company / contact (denormalised for fast table queries) ────────────────
    company_name  = models.CharField(max_length=255, blank=True, default="")
    contact_name  = models.CharField(max_length=255, blank=True, default="")
    contact_email = models.EmailField(blank=True, default="")
    contact_phone = models.CharField(max_length=50, blank=True, default="")
    accounts_contact_email = models.EmailField(blank=True, default="")

    # ── Financial (Zoho field mapping) ─────────────────────────────────────────

    discount             = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount_code        = models.CharField(max_length=100, blank=True, default="")
    pre_tax_amount       = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    tax_amount           = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    total_amount         = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    add_ons_total_amount = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    currency             = models.CharField(max_length=10, choices=Currency.choices, default=Currency.USD)
    ticket_tier          = models.CharField(max_length=50, choices=TicketTier.choices, blank=True, default="")
    delegate_count       = models.PositiveIntegerField(default=1)

    # ── Website intake metadata ────────────────────────────────────────────────
    source    = models.CharField(max_length=20, choices=Source.choices, default=Source.MANUAL, db_index=True)
    form_name = models.CharField(max_length=255, blank=True, default="")
    form_url  = models.CharField(max_length=500, blank=True, default="")
    packages  = models.JSONField(default=list, blank=True)

    # ── Payment ────────────────────────────────────────────────────────────────
    payment_status = models.CharField(
        max_length=30, choices=PaymentStatus.choices,
        blank=True, default="", db_index=True,
    )
    payment_date     = models.DateField(null=True, blank=True)
    payment_due_date = models.DateField(null=True, blank=True)
    payment_type = models.CharField(
        max_length=30, blank=True, default="",
        choices=PaymentType.choices,
    )
    paid_or_free = models.CharField(
        max_length=20, choices=PaidOrFree.choices, blank=True, default="",
    )
    paid_free = models.CharField(max_length=20, blank=True, default="")  # legacy

    # ── Reference ──────────────────────────────────────────────────────────────
    reference    = models.CharField(max_length=100, blank=True, default="")
    parent_code  = models.CharField(max_length=100, blank=True, default="")
    request_date = models.DateField(null=True, blank=True)
    notes        = models.TextField(blank=True, default="")
    add_ons      = models.TextField(blank=True, default="")
    attendance   = models.CharField(max_length=100, blank=True, default="")
    created_at   = models.DateTimeField(default=timezone.now)
    updated_at   = models.DateTimeField(auto_now=True)
    updated_by   = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, blank=True,
        on_delete=models.SET_NULL,
        related_name="updated_bookings",
    )

    class Meta:
        db_table = "book_events"
        ordering = ["-created_at"]
        indexes  = [
            models.Index(fields=["invoice_number"]),
            models.Index(fields=["event_code"]),
            models.Index(fields=["payment_status"]),
            models.Index(fields=["contact_email"]),
            models.Index(fields=["company_name"]),
            models.Index(fields=["created_at"]),
            models.Index(fields=["updated_at"]),
            models.Index(fields=["ticket_tier"]),
            models.Index(fields=["paid_or_free"]),
            # request_date and invoice_date carried NO index of any kind, and both
            # are read on every bookings request: request_date is the default sort
            # (book_delegate/views.py ordering = ["-_sort_request_date"]) and the
            # pair is the period window (period_date_fields).
            #
            # Spelled as expressions rather than fields=["-request_date", "-id"]
            # because that form emits DESC NULLS FIRST, which is a DIFFERENT index
            # from the DESC NULLS LAST the DDL specifies. These names and the
            # column lists must stay byte-identical to the CREATE INDEX statements
            # in backend/sql/2026_08_perf_indexes.sql.
            models.Index(
                models.F("request_date").desc(nulls_last=True),
                models.F("id").desc(),
                name="book_events_reqdate_id_idx",
            ),
            models.Index(
                models.F("invoice_date").desc(nulls_last=True),
                models.F("id").desc(),
                name="book_events_invdate_id_idx",
            ),
        ]

    def __str__(self):
        return f"{self.invoice_number} — {self.event_code}"

    # ── Invoice columns that a DELEGATE row is exported with ──────────────────
    #
    # WHY THIS LIST EXISTS. A delegate row in the Data API export
    # (dataapi/serializers.py DataApiDelegateSerializer) is one delegate plus the
    # half of the booking that lives on the invoice: the dates, the billing
    # company, the accounts contact, the sales executive, and the five payment
    # values the delegate inherits whenever it carries no delegate_* override.
    # Change any of those on the invoice and the exported delegate row changes,
    # while book_delegates.updated_at does not move at all.
    #
    # That was harmless while updated_at only decided table sort order, and
    # book_delegate/views.py says so. It is NOT harmless for an incremental
    # consumer. The export's delta filter is ?updated_since=<ts> against
    # book_delegates.updated_at (dataapi/views.py DelegateDataViewSet), so an
    # invoice-level payment edit used to leave a Google Sheet showing the old
    # payment status for good: the row's cells had changed, its watermark had
    # not, and no later sync would ever hand it over again.
    #
    # ONLY EXPORT-VISIBLE COLUMNS BELONG HERE. Every name added widens what
    # counts as "the delegates changed" and puts more rows through the delta
    # feed; total_amount, tax_amount, currency, form_url and the rest are
    # invoice-only and deliberately absent. sales_executive is spelled with its
    # attname because that is what .values() returns and what the in-memory
    # attribute holds without a fetch.
    DELEGATE_EXPORT_FIELDS = (
        "request_date", "invoice_date", "payment_due_date",
        "event_name", "parent_code", "company_name", "accounts_contact_email",
        "sales_executive_id",
        "payment_status", "payment_type", "payment_date",
        "paid_or_free", "ticket_tier",
    )

    def _export_field_changed(self, prev: dict, attname: str) -> bool:
        """
        Did `attname` move between the stored row `prev` and this instance?

        BOTH SIDES GO THROUGH to_python, for the reason spelled out at the read
        site: the database hands back a date or an int, while an in-memory
        instance may still hold the ISO string or the numeric string an importer
        assigned, and comparing those two raw is unequal every time. A FK's
        attname has no field of its own to normalise with, so it is compared as
        the plain integer both sides already are.

        None AND "" COUNT AS THE SAME VALUE on a text column. Django stores
        blank=True CharFields as "", but a caller that assigns None leaves the
        attribute None until the row is reloaded; treating that pair as a change
        would stamp every delegate on the invoice on saves that wrote nothing.
        The error only ever costs a spurious row in the delta feed, which an
        id-keyed upsert absorbs, whereas the reverse error loses an edit.
        """
        current = getattr(self, attname, None)
        stored = prev.get(attname)
        try:
            field = self._meta.get_field(attname)
        except FieldDoesNotExist:
            # sales_executive_id and anything else named by attname rather than
            # by field name. Compared raw; both sides are already ints or None.
            return stored != current
        stored = field.to_python(stored)
        current = field.to_python(current)
        if isinstance(field, (models.CharField, models.TextField)):
            stored = stored or ""
            current = current or ""
        return stored != current

    def save(self, *args, **kwargs):
        if not self.invoice_number:
            raise ValueError("invoice_number must be pre-generated by the website.")

        # What moved on this invoice? Read once, here, as the columns below and
        # nothing else — save() did not previously load the stored row for any
        # reason, so there is nothing to reuse and this is a genuinely new read.
        # It is keyed on the pk, and it only happens on UPDATE: a create has no
        # delegates yet, so there is nothing to propagate to.
        #
        # TWO DIFFERENT CASCADES READ THIS ONE SNAPSHOT. request_date and
        # invoice_date drive the booked_on write at the foot of save(); the rest
        # of DELEGATE_EXPORT_FIELDS drive the delegates' updated_at stamp beside
        # it. One SELECT serves both, which is why the read is widened rather
        # than duplicated.
        _dates_changed = False
        _prev = None
        if self.pk:
            _prev = (BookEvent.objects
                     .filter(pk=self.pk)
                     .values(*self.DELEGATE_EXPORT_FIELDS)
                     .first())
            if _prev is not None:
                # BOTH SIDES NORMALISED THROUGH to_python BEFORE COMPARING.
                # The database returns datetime.date, but an in-memory instance
                # can legitimately hold a STRING — BookEvent.objects.create(
                # request_date="2026-01-01") leaves the attribute a str until it
                # is reloaded, and several importers assign ISO strings directly.
                # Comparing date(2026,1,1) to "2026-01-01" is always unequal, so
                # without this every save of an unchanged invoice would rewrite
                # every one of its delegate rows.
                _dates_changed = (
                    self._export_field_changed(_prev, "request_date")
                    or self._export_field_changed(_prev, "invoice_date")
                )
        if self.event_code:
            import re
            match = re.search(r'(\d{2,4})$', self.event_code)
            if match:
                num_str = match.group(1)
                self.edition = int(f"20{num_str}" if len(num_str) == 2 else num_str)
                self.event_code = re.sub(r'\s*-?\s*\d{2,4}$', '', self.event_code).strip()
            
            # Dynamically fetch clean name from master Event catalogue and append edition year
            from events.models import Event
            master_event = Event.objects.filter(event_code=self.event_code).first()
            if master_event:
                clean_name = re.sub(r'\s*\d{4}$', '', master_event.name).strip()
                if self.edition:
                    self.event_name = f"{clean_name} {self.edition}"
                else:
                    self.event_name = clean_name

        # Spelling, not meaning. canonicalize() only ever swaps a code for a
        # member of the closed list it already key-matches (case- and
        # spacing-insensitively); anything off that list is returned untouched.
        # It sits HERE, on save(), rather than at the webhook call site, because
        # the webhook is not the only writer: the importer, the bulk-update
        # engine and the DRF serializers all reach this line, and a chokepoint
        # is the only version of this that cannot be bypassed by a new one.
        args, kwargs = canonicalize_on_save(self, args, kwargs)
        super().save(*args, **kwargs)

        # A SANCTIONED queryset .update().
        #
        # The project rule is per-object save() because BookDelegate.save() is
        # load-bearing; it derives edition and event_code, inherits booking_code,
        # and reads the previous payment status to decide delegate_count. None of
        # that is relevant here. This writes one derived column and one timestamp
        # and runs no derivation, so routing it through save() would re-run all of
        # the above plus one extra SELECT for every delegate on the invoice, which
        # is the cost this workstream exists to remove. Scope is deliberately two
        # columns, one table, one invoice; anything wider goes back through save().
        #
        # Filtered on invoice_id, NOT on pk, and NOT on invoice_number.
        # BookDelegate.invoice is a to_field FK: field.name is "invoice",
        # field.attname is "invoice_id", and field.column is "invoice_number".
        # Only the first two are ORM query names — filter(invoice_number=...)
        # raises FieldError, because invoice_number is the DB column and not a
        # field Django will resolve. invoice_id is the attname and holds the
        # invoice-number STRING, so this compares number to number. Comparing to
        # self.pk would compare a varchar column to an integer and match nothing.
        # The emitted SQL is:
        #     UPDATE "book_delegates" SET "booked_on" = %s, "updated_at" = %s
        #     WHERE "book_delegates"."invoice_number" = %s
        # with either assignment dropped when its own cascade did not fire.
        #
        # updated_at RIDES ALONG, and is the reason this block now runs for more
        # than a date change. See DELEGATE_EXPORT_FIELDS above: an invoice-level
        # edit rewrites cells of the delegate export while book_delegates
        # .updated_at stands still, and ?updated_since= reads exactly that
        # column, so the incremental consumer never learns the row changed. A
        # queryset .update() does not fire auto_now — the ORM never instantiates
        # the rows, so no field's pre_save() runs — hence the explicit stamp.
        # timezone.now() rather than a literal, so it is tz-aware under USE_TZ
        # and stored as UTC like every other timestamp here.
        #
        # STILL AT MOST ONE STATEMENT. The two cascades share a snapshot and a
        # WHERE clause, so they are merged into one UPDATE rather than issued as
        # two; a save that changed neither issues none.
        _delegate_export_changed = _prev is not None and any(
            self._export_field_changed(_prev, name)
            for name in self.DELEGATE_EXPORT_FIELDS
        )
        if _dates_changed or _delegate_export_changed:
            from book_delegate.models import BookDelegate
            _delegate_writes = {}
            if _dates_changed:
                _delegate_writes["booked_on"] = self._booked_on_expression()
            if _delegate_export_changed:
                _delegate_writes["updated_at"] = timezone.now()
            BookDelegate.objects.filter(invoice_id=self.invoice_number).update(
                **_delegate_writes
            )

    def _booked_on_expression(self):
        """
        Each delegate's booked_on, as ONE expression the cascade can hand to a
        queryset .update().

        It has to be an expression rather than a literal date, because a
        delegate may carry its OWN request or invoice date now
        (book_delegate/models.py delegate_request_date). A literal would set
        every row on the invoice to the invoice's date and silently destroy
        those overrides, which is the whole thing they exist to express. Same
        chain as BookDelegate._derive_booked_on, evaluated per row in SQL,
        COALESCE(delegate_request_date, invoice.request_date,
                 delegate_invoice_date, invoice.invoice_date).

        The invoice's two dates are passed as VALUES rather than read back
        through the join, so the update sees what this save is writing rather
        than what the row held before it. A null one is left out of the chain
        entirely; Value(None) reaches the database as an untyped parameter and
        the cast it would need buys nothing, since a NULL term can never be the
        one COALESCE returns.
        """
        from django.db.models import DateField, Value
        from django.db.models.functions import Coalesce

        def _as_date(attname):
            # to_python for the reason given at the snapshot read above: an
            # in-memory instance can still hold the ISO STRING an importer or a
            # serializer assigned, and that must not reach the database as the
            # parameter of a date COALESCE.
            return self._meta.get_field(attname).to_python(getattr(self, attname, None))

        terms = ["delegate_request_date"]
        request_date = _as_date("request_date")
        if request_date is not None:
            terms.append(Value(request_date, output_field=DateField()))
        terms.append("delegate_invoice_date")
        invoice_date = _as_date("invoice_date")
        if invoice_date is not None:
            terms.append(Value(invoice_date, output_field=DateField()))
        return Coalesce(*terms, output_field=DateField())

    @classmethod
    def auto_assign_sales(cls, event_code: str):
        """
        The sales executive for `event_code`, as the EVENTS TAB defines it.

        One resolver for every path that creates or re-homes a booking (website
        intake, the Bookings modal, the importers) so a manually-entered booking
        and a webhook-created one on the same event cannot end up owned by
        different people.

        Order, and why:
          1. Event.sales_executive — the FK the Events tab writes, and which
             Event.save() keeps in step with the `sales_team` text field in both
             directions (events/models.py:104-152). This is the authoritative
             answer whenever the event has been maintained through the UI.
          2. User.assigned_events — the older m2m this method used exclusively.
             Kept as the fallback so events assigned only through that relation
             still resolve exactly as they did before.

        Returns None when neither answers; callers must treat "unassigned" as a
        legitimate outcome rather than an error, because an event can genuinely
        have no sales executive yet.
        """
        from accounts.models import User
        from events.models import Event

        event = (
            Event.objects
            .filter(event_code=event_code)
            .select_related("sales_executive")
            .first()
        )
        if event and event.sales_executive_id:
            return event.sales_executive
        return (
            User.objects
            .filter(role=User.Role.SALES, assigned_events__event_code=event_code)
            .first()
        )

class WebhookLog(models.Model):
    class Status(models.TextChoices):
        SUCCESS   = "success",   "Success"
        FAILED    = "failed",    "Failed"
        DUPLICATE = "duplicate", "Duplicate"

    source_ip      = models.GenericIPAddressField(null=True, blank=True)
    payload        = models.JSONField(default=dict)
    headers        = models.JSONField(default=dict)
    response       = models.JSONField(default=dict)
    status         = models.CharField(max_length=20, choices=Status.choices, default=Status.SUCCESS)
    http_status    = models.PositiveIntegerField(default=200)
    invoice_number = models.CharField(max_length=100, blank=True, default="")
    event_code     = models.CharField(max_length=50, blank=True, default="")
    error_message  = models.TextField(blank=True, default="")
    created_at     = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = "webhook_logs"
        ordering = ["-created_at"]
        indexes  = [
            models.Index(fields=["status"]),
            models.Index(fields=["created_at"]),
            models.Index(fields=["invoice_number"]),
        ]

    def __str__(self):
        return f"[{self.status}] {self.invoice_number or '—'} @ {self.created_at:%Y-%m-%d %H:%M}"


class SyncLog(models.Model):
    class Status(models.TextChoices):
        SUCCESS = "success", "Success"
        FAILED  = "failed",  "Failed"

    dataset        = models.CharField(max_length=50, unique=True)
    last_synced_at = models.DateTimeField(null=True, blank=True)
    last_status    = models.CharField(max_length=20, choices=Status.choices, default=Status.SUCCESS)
    records_synced = models.IntegerField(default=0)
    error_message  = models.TextField(blank=True, default="")

    class Meta:
        db_table = "sync_logs"

    def __str__(self):
        return f"{self.dataset}: {self.last_status} ({self.records_synced} rows) at {self.last_synced_at}"
