# Generated by Django 5.2.8 on 2026-08-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sync', '0002_googlesheetsynclog_gs_logs_status_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetsynclog',
            name='sync_type',
            field=models.CharField(choices=[('bookings', 'Bookings'), ('events', 'Events'), ('full_sync', 'Full Sync'), ('crm_mirror', 'CRM Mirror')], db_index=True, max_length=20),
        ),
    ]
