# Generated by Django 5.2.8 on 2026-08-18 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sync', '0003_alter_googlesheetsynclog_sync_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheetsynclog',
            name='sync_type',
            field=models.CharField(choices=[('bookings', 'Bookings'), ('events', 'Events'), ('full_sync', 'Full Sync'), ('crm_mirror', 'CRM Mirror'), ('sheet_target', 'Sheet Target')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SheetSyncTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What this push is for.', max_length=200)),
                ('spreadsheet_id', models.CharField(help_text='Google spreadsheet id. A pasted sheet URL is reduced to its id on save.', max_length=200)),
                ('tab_name', models.CharField(help_text='Tab to write. Created on the first run if it does not exist.', max_length=200)),
                ('module', models.CharField(db_index=True, help_text="Catalogue key, see sync/catalog.py. e.g. 'bookings'.", max_length=50)),
                ('columns', models.JSONField(default=list, help_text='Column keys, in sheet order. e.g. ["delegate_name", "delegate_email"].')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Never run'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='never', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_sync_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sheet sync target',
                'verbose_name_plural': 'Sheet sync targets',
                'db_table': 'google_sheet_sync_targets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module'], name='gs_target_module_idx')],
                'constraints': [models.UniqueConstraint(fields=('spreadsheet_id', 'tab_name'), name='one_target_per_tab')],
            },
        ),
    ]
