# Generated by Django 5.2.8 on 2026-09-09 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(blank=True, default='', max_length=64)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('redirect_uris', models.JSONField(default=list)),
                ('grant_types', models.JSONField(default=list)),
                ('response_types', models.JSONField(default=list)),
                ('scope', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MCP OAuth client',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('redirect_uri_provided_explicitly', models.BooleanField(default=True)),
                ('code_challenge', models.CharField(max_length=255)),
                ('scopes', models.JSONField(default=list)),
                ('resource', models.CharField(blank=True, default='', max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_auth_codes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='mcp_auth.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='PendingAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('redirect_uri_provided_explicitly', models.BooleanField(default=True)),
                ('code_challenge', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=500)),
                ('scopes', models.JSONField(default=list)),
                ('resource', models.CharField(blank=True, default='', max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending', to='mcp_auth.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh')], db_index=True, max_length=10)),
                ('scopes', models.JSONField(default=list)),
                ('resource', models.CharField(blank=True, default='', max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mcp_auth.issuedtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_auth_tokens', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mcp_auth.oauthclient')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind'], name='mcp_auth_is_user_id_e5130f_idx')],
            },
        ),
    ]
