# Generated by Django 5.2.8 on 2026-09-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthclient',
            name='token_endpoint_auth_method',
            field=models.CharField(default='none', max_length=32),
        ),
    ]
