# Generated by Django 5.2.8 on 2026-09-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_auth', '0002_oauthclient_token_endpoint_auth_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthclient',
            name='client_secret_hash',
        ),
        migrations.AddField(
            model_name='oauthclient',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
