# Generated by Django 5.2.8 on 2026-09-08 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_delegate', '0019_bookdelegate_book_delegates_event_email_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('edition', models.IntegerField(blank=True, db_index=True, null=True)),
                ('attendee_type', models.CharField(choices=[('delegate', 'Delegate'), ('speaker', 'Speaker')], db_index=True, default='delegate', max_length=16)),
                ('attendee_name', models.CharField(max_length=255)),
                ('attendee_email', models.CharField(blank=True, default='', max_length=254)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='Checked-in', max_length=20)),
                ('checked_in_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('qr_scan', 'QR scan'), ('manual', 'Manual')], default='qr_scan', max_length=16)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_checkins', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='book_delegate.bookdelegate')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-checked_in_at', '-id'],
                'indexes': [models.Index(models.F('event_code'), models.OrderBy(models.F('checked_in_at'), descending=True), name='att_event_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('delegate',), name='attendance_one_row_per_delegate')],
            },
        ),
    ]
