# Generated by Django 5.2.8 on 2026-09-10 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('book_delegate', '0019_bookdelegate_book_delegates_event_email_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceQrEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('edition', models.IntegerField(blank=True, db_index=True, null=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_email_logs', to='book_delegate.bookdelegate')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_email_sends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_qr_email_log',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'sent')), fields=('delegate',), name='attendance_qr_email_one_sent_per_delegate')],
            },
        ),
    ]
