# Generated by Django 5.2.8 on 2026-08-10 14:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('participation_type', models.CharField(blank=True, default='', max_length=50)),
                ('speaker_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('qc_grade', models.CharField(blank=True, default='', max_length=10)),
                ('qc_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sales_pitch_factor', models.CharField(blank=True, default='', max_length=255)),
                ('presentation_theme', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_speaker', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_company', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin_followers', models.PositiveIntegerField(blank=True, null=True)),
                ('speaker_slot_status', models.CharField(blank=True, default='', max_length=30)),
                ('sponsorship_status', models.CharField(blank=True, default='', max_length=30)),
                ('spex_remarks', models.TextField(blank=True, default='')),
                ('agenda_slot', models.CharField(blank=True, default='', max_length=150)),
                ('revenue_possibility', models.CharField(blank=True, default='', max_length=20)),
                ('internal_footnotes_mr', models.TextField(blank=True, default='')),
                ('slot_recommendation_mr', models.TextField(blank=True, default='')),
                ('agenda_addition', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposal_submissions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_proposal_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal Submission',
                'verbose_name_plural': 'Proposal Submissions',
                'db_table': 'proposal_submissions',
                'ordering': ['-submission_date', '-id'],
                'indexes': [models.Index(fields=['event_code'], name='proposal_su_event_c_1bd6eb_idx'), models.Index(fields=['submission_date'], name='proposal_su_submiss_512f81_idx'), models.Index(fields=['speaker_slot_status'], name='proposal_su_speaker_0f204b_idx'), models.Index(fields=['sponsorship_status'], name='proposal_su_sponsor_5f6817_idx'), models.Index(fields=['created_at'], name='proposal_su_created_7313a4_idx')],
            },
        ),
    ]
