# Generated by Django 5.2.8 on 2026-08-10 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0001_initial'),
        ('proposal_submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsubmission',
            name='source_paper_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_submissions', to='paper_review.paperreview'),
        ),
        migrations.AddConstraint(
            model_name='proposalsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('source_paper_review__isnull', False)), fields=('source_paper_review',), name='one_auto_proposal_per_paper_review'),
        ),
    ]
