# Generated by Django 5.2.8 on 2026-08-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_submission', '0002_proposalsubmission_source_paper_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsubmission',
            name='import_batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
