# Generated by Django 5.2.8 on 2026-08-13 22:13

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_review', '0005_paperreview_paper_review_dupe_idx'),
        ('proposal_submission', '0003_proposalsubmission_import_batch_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proposalsubmission',
            index=models.Index(models.F('event_code'), django.db.models.functions.text.Lower('email'), name='proposal_dupe_idx'),
        ),
    ]
