# Generated by Django 5.2.8 on 2026-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_submission', '0005_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsubmission',
            name='panel_approached',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalsubmission',
            name='panel_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='proposalsubmission',
            name='panel_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposalsubmission',
            name='risk_assessment_live',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proposalsubmission',
            name='speaker_slot_reoffered',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
