# Generated by Django 5.2.8 on 2026-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_submission', '0006_proposalsubmission_panel_approached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsubmission',
            name='added_to_agenda',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='proposalsubmission',
            name='revenue_possibility',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
