# Generated by Django 5.2.8 on 2026-09-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal_submission', '0008_unwrap_linkedin_anchors'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsubmission',
            name='speaking_slot_assignment',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
