# Generated by Django 5.2.8 on 2026-09-04 15:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_delegate', '0019_bookdelegate_book_delegates_event_email_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('edition', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_issues', to='book_delegate.bookdelegate')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pre_event_docs_badge_issues',
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(models.F('event_code'), models.F('edition'), models.OrderBy(models.F('issued_at'), descending=True), name='ped_badge_event_idx'), models.Index(models.F('delegate'), models.OrderBy(models.F('issued_at'), descending=True), name='ped_badge_delegate_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(db_index=True, max_length=50)),
                ('edition', models.IntegerField(blank=True, db_index=True, null=True)),
                ('per_table', models.PositiveSmallIntegerField(default=6)),
                ('rounds', models.PositiveSmallIntegerField(default=3)),
                ('tables', models.PositiveSmallIntegerField()),
                ('repeat_pairs', models.PositiveIntegerField(default=0)),
                ('floor_repeats', models.PositiveIntegerField(default=0)),
                ('assignment', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networking_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pre_event_docs_networking_plans',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(models.F('event_code'), models.F('edition'), models.OrderBy(models.F('created_at'), descending=True), name='ped_plan_event_idx')],
            },
        ),
    ]
