# Generated by Django 5.2.8 on 2026-09-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_event_docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkingplan',
            name='per_table',
        ),
    ]
