# Generated by Django 5.2.8 on 2026-08-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_lead_archived_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_all_access',
            field=models.BooleanField(default=False, help_text='Full access to every module, ignoring the permission rows below.'),
        ),
        migrations.AlterField(
            model_name='teamactivitylog',
            name='action_type',
            field=models.CharField(choices=[('member_moved', 'Member Moved'), ('member_removed', 'Member Removed'), ('member_added', 'Member Added'), ('lead_assigned', 'Lead Assigned'), ('team_renamed', 'Team Renamed'), ('team_deleted', 'Team Deleted'), ('team_archived', 'Team Archived'), ('team_created', 'Team Created'), ('permissions_changed', 'Permissions Changed')], max_length=30),
        ),
        migrations.CreateModel(
            name='TeamPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='teams.team')),
            ],
            options={
                'db_table': 'team_permissions',
                'ordering': ['module'],
                'unique_together': {('team', 'module')},
            },
        ),
    ]
