# Generated by Django 5.2.8 on 2026-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0021_bookevent_payment_status_iq_staff'),
        ('webhooks', '0004_backfill_webhooklog_received_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['received_at'], name='wh_ev_received_idx'),
        ),
    ]
