# Generated by Django 5.2.8 on 2026-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookapikey',
            name='target',
            field=models.CharField(blank=True, choices=[('bookings', 'Bookings'), ('tickets', 'Tickets'), ('paper_review', 'Paper reviews')], default='', help_text='Optional: restrict to one ingest endpoint; empty = every endpoint', max_length=20),
        ),
    ]
