# Generated by Django 5.2.8 on 2026-08-31 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_webhookapikey_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookapikey',
            name='mre',
            field=models.ForeignKey(blank=True, help_text='Paper review form links only: the reviewer this form belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_review_form_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webhookapikey',
            name='target',
            field=models.CharField(blank=True, choices=[('bookings', 'Bookings'), ('tickets', 'Tickets'), ('paper_review', 'Paper reviews'), ('paper_review_form', 'Paper review form (MRE link)')], default='', help_text='Optional: restrict to one ingest endpoint; empty = every endpoint', max_length=20),
        ),
    ]
